site_name: Caio's personal website
site_url: https://caiomts.github.io/
site_author: Caio Mescouto Terra de Souza

#repo_name: /caiomts/caiomts.github.io
#repo_url: https://github.com/caiomts/caiomts.github.io
#edit_uri: edit/main/docs/

nav:
  - Home: 
      - index.md
  - Projects: 
      - projects.md

theme:
  name: material
  palette:
    - scheme: default
      primary: light green
      accent: indigo
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      primary: light green
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode  
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    admonition:
      example: octicons/stack-16
      annotation: material/plus-circle-outline
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.share
    - header.autohide
    - content.action.view
    - content.code.annotate

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/caiomts
      name: github.com/caiomts

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/caiomts/
      name: in/caiomts/

plugins:
  - tags
  - search
  #- blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

extra_css:
  - stylesheets/extra.css
